Создайте матрицу 3 на 3, заполненную числами от 1 до 9
Прибавьте к ней матрицу с единицами на диагонале
Умножьте полученную матрицу на вектор (1, 2, 3)
Посчитайте обратную матрицу к полученной матрице

In [1]:
import numpy as np

In [2]:
A = np.array ([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
B = np.eye(3)

In [6]:
C = A+B
C

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [5]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [22]:
D = C*v
D

array([[ 2.,  4.,  9.],
       [ 4., 12., 18.],
       [ 7., 16., 30.]])

In [32]:
# обратная матрица
E = np.linalg.inv(D)
E

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-5.00000000e-01,  2.50000000e-01,  2.22044605e-17],
       [ 1.66666667e+00,  3.33333333e-01, -6.66666667e-01]])

In [34]:
# проверка
M = np.array(np.round(E@D), dtype=int)
M

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])